savedPath.member.picture=c:/member/picture/upload/
savedPath.summernote.image=c:/summernote/images
savedPath.pds.files=c:/pds/files
savedPath.log.files=c:/log
savedPath.login.user.log.fileName=login_user_log.csv