savedPath.member.picture=c:/member/picture/upload/
savedPath.summernote.image=c:/summernote/images
savedPath.upload.files=c:/static/upload/
savedPath.log.files=c:/log
savedPath.login.user.log.fileName=login_user_log.csv